services:
    laravel-docker:
        depends_on:
            - mysql
            - redis
        container_name: itaprofilesbackend-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        command: >
            bash -c "composer install && cp .env.docker .env && php artisan key:generate && php artisan migrate:fresh && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=80 && php artisan config:cache"
        networks:
            - itabackend

    mysql:
        container_name: itaprofilesbackend-mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
        networks:
            - itabackend
    
    redis:
        container_name: itaprofilesbackend-redis
        image: redis:latest
        command: ["redis-server", "/etc/redis/redis.conf"]
        ports:
            - "6379:6379"
        volumes:
          - ./docker/redis/.conf/redis.conf:/etc/redis/redis.conf
          - ./docker/redis/data:/var/lib/redis/
        networks:
            - itabackend

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9015:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - itabackend

networks:
    itabackend:
