version: '3.7'

services:
    webserver:
        container_name: webserver
        image: nginx:latest
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html
        build:
            context: .
            target: nginx-stage
        depends_on:
            - php
            - node

    php:
        container_name: php
        image: php:8.1-fpm
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        build:
            context: .
            target: php-stage
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html

    node:
        container_name: node
        image: node:22.2.0
        restart: unless-stopped
        tty: true
        build:
            context: .
            target: node-stage
        entrypoint:
            - /var/www/html/entrypoint_node.sh
        volumes:
            - ./:/var/www/html
        expose:
            - "80"
        environment:
            - NODE_ENV=development

    mysql:
        container_name: mysql
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
