services:
    laravel-docker:
        depends_on:
            - mysql
        container_name: itaprofilesbackend-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        networks:
            - itabackend

    mysql:
        container_name: itaprofilesbackend-mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
        networks:
            - itabackend

    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "9015:80"
        environment:
            - PMA_ARBITRARY=1
        networks:
            - itabackend

networks:
    itabackend:
