services:
    frontend:
        depends_on:
            - mysql
        container_name: itaprofiles-frontend
        command: ["npm", "run", "start"]
        build:
            context: .
            dockerfile: FrontendDockerFile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - itaprofiles

    backend:
        depends_on:
            - mysql
        container_name: itaprofiles-backend
        build:
            context: .
            dockerfile: BackendDockerFile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        networks:
            - itaprofiles

    mysql:
        container_name: itaprofilesbackend-mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
        networks:
            - itaprofiles

    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "9015:80"
        environment:
            - PMA_ARBITRARY=1
        networks:
            - itaprofiles

networks:
    itaprofiles:
