version: '3.8'

services:
    app:
        build: .
        ports:
            - "80:80"
            - "8000:8000"
            - "3306:3306"
            - "6379:6379"
        volumes:
            - .:/var/www/html
        container_name: ita-profiles
