name: backend_check

on:
  pull_request:
    branches:
      - main

jobs:
  pr_check:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - "6379:6379"
        volumes:
          - ./docker/redis/.conf/redis.conf:/usr/local/etc/redis/redis.conf
          - ./docker/redis/data:/data

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Configurar .env para pruebas
        run: |
          echo "APP_KEY=" >> .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_test" >> .env
          echo "DB_USERNAME=laravel_user" >> .env
          echo "DB_PASSWORD=secret" >> .env

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Instalar dependencias
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generar clave de aplicación
        run: php artisan key:generate

      - name: Ejecutar migraciones y seeds
        run: php artisan migrate --seed

      - name: Inicializar passport
        run: php artisan passport:install

      - name: Instalar PHPUnit
        run: composer require --dev phpunit/phpunit

      - name: Ejecutar PHPUnit
        run: php artisan test
