name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh {{ secrets.SSH_USERNAME }}@{{ secrets.SSH_HOST_URL }} "cd /var/www/html/ita-profiles-backend && git pull origin develop"

        env:
          SSH_PASSWORD: ${{ secrets.SSH_KEY }}
          SSH_HOST_URL: ${{ secrets.SSH_HOST_URL }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
