name: Laravel CI

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Instalar dependencias
        run: composer install

      - name: Copiar el archivo de entorno
        run: cp .env.example .env

      - name: Configurar .env para pruebas
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/g' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/g' .env
          sed -i 's/DB_DATABASE=homestead/DB_DATABASE=laravel_test/g' .env
          sed -i 's/DB_USERNAME=homestead/DB_USERNAME=laravel_user/g' .env
          sed -i 's/DB_PASSWORD=secret/DB_PASSWORD=secret/g' .env

      - name: Generar clave de aplicación
        run: php artisan key:generate

      - name: Ejecutar migraciones y seeds
        run: php artisan migrate:fresh --seed

      - name: Ejecutar pruebas unitarias
        run: php artisan test
